# Generated by Django 3.2 on 2023-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='XXXX', max_length=36, null=True, verbose_name='Код подтверждения'),
        ),
    ]
