# Generated by Django 3.2 on 2023-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', editable=False, error_messages={'validators': 'Вы выбрали несуществующую роль'}, max_length=25, verbose_name='Роль'),
        ),
    ]
