# Generated by Django 3.2 on 2023-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230906_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='XXXX', max_length=256, null=True, unique=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', error_messages={'validators': 'Вы выбрали несуществующую роль'}, max_length=25, verbose_name='Роль'),
        ),
    ]
